"""Generic single-database configuration with an async dbapi."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c4f9570e49'
down_revision = '69f6c2135bf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.add_column('otp_codes', sa.Column('request_ip', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_otp_codes_created_at'), 'otp_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_request_ip'), 'otp_codes', ['request_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_request_ip'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_created_at'), table_name='otp_codes')
    op.drop_column('otp_codes', 'request_ip')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
