"""Generic single-database configuration with an async dbapi."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f6c2135bf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure required extensions exist before creating trgm indexes
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.Enum('LITRE', 'KG', 'PIECE', name='product_unit'), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('requires_bottle', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', 'DELIVERY', name='user_role'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wallet_balance_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_name_trgm', 'users', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('geocoding_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_area'), 'addresses', ['area'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('adjustments_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'OVERDUE', name='invoice_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'year', 'month', name='uq_invoice_customer_period')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('notifications_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('PUSH', 'SMS', 'WHATSAPP', name='notification_channel'), nullable=False),
    sa.Column('template', sa.String(length=120), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_user_id'), 'notifications_log', ['user_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('delivery_boy_id', sa.UUID(), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_boy_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_delivery_boy_id'), 'routes', ['delivery_boy_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'ALTERNATE', 'WEEKLY', 'CUSTOM', name='subscription_frequency'), nullable=False),
    sa.Column('custom_days', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', name='subscription_status'), nullable=False),
    sa.Column('pause_from', sa.Date(), nullable=True),
    sa.Column('pause_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_product_id'), 'subscriptions', ['product_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('change_paise', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('reference_id', sa.String(length=120), nullable=True),
    sa.Column('balance_after_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_customer_id'), 'wallet_transactions', ['customer_id'], unique=False)
    op.create_table('delivery_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'SKIPPED', 'FAILED', name='delivery_order_status'), nullable=False),
    sa.Column('delivered_quantity', sa.Integer(), nullable=True),
    sa.Column('bottles_returned', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_boy_id', sa.UUID(), nullable=True),
    sa.Column('cutoff_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_boy_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'delivery_date', name='uq_delivery_sub_date')
    )
    op.create_index(op.f('ix_delivery_orders_customer_id'), 'delivery_orders', ['customer_id'], unique=False)
    op.create_index('ix_delivery_orders_date_status', 'delivery_orders', ['delivery_date', 'status'], unique=False)
    op.create_index(op.f('ix_delivery_orders_delivery_date'), 'delivery_orders', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_orders_product_id'), 'delivery_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_subscription_id'), 'delivery_orders', ['subscription_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('WALLET', 'RAZORPAY_UPI', 'RAZORPAY_CARD', 'CASH', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=120), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=120), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('raw_response', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', name='uq_customer_single_route'),
    sa.UniqueConstraint('route_id', 'customer_id', name='uq_route_customer')
    )
    op.create_index(op.f('ix_route_stops_customer_id'), 'route_stops', ['customer_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('subscription_schedule_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_override', sa.Integer(), nullable=True),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'date', name='uq_subscription_override_date')
    )
    op.create_index(op.f('ix_subscription_schedule_overrides_date'), 'subscription_schedule_overrides', ['date'], unique=False)
    op.create_index(op.f('ix_subscription_schedule_overrides_subscription_id'), 'subscription_schedule_overrides', ['subscription_id'], unique=False)
    op.create_table('bottle_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('delivery_order_id', sa.UUID(), nullable=True),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('DELIVERED', 'RETURNED', 'ADJUSTMENT', name='bottle_reason'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bottle_ledger_created_at'), 'bottle_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_bottle_ledger_customer_id'), 'bottle_ledger', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bottle_ledger_delivery_order_id'), 'bottle_ledger', ['delivery_order_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('delivery_order_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_bottle_ledger_delivery_order_id'), table_name='bottle_ledger')
    op.drop_index(op.f('ix_bottle_ledger_customer_id'), table_name='bottle_ledger')
    op.drop_index(op.f('ix_bottle_ledger_created_at'), table_name='bottle_ledger')
    op.drop_table('bottle_ledger')
    op.drop_index(op.f('ix_subscription_schedule_overrides_subscription_id'), table_name='subscription_schedule_overrides')
    op.drop_index(op.f('ix_subscription_schedule_overrides_date'), table_name='subscription_schedule_overrides')
    op.drop_table('subscription_schedule_overrides')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_customer_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_delivery_orders_subscription_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_product_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_delivery_date'), table_name='delivery_orders')
    op.drop_index('ix_delivery_orders_date_status', table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_customer_id'), table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_index(op.f('ix_wallet_transactions_customer_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_subscriptions_product_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_routes_delivery_boy_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_notifications_log_user_id'), table_name='notifications_log')
    op.drop_table('notifications_log')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_area'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index('ix_users_name_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('users')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
